/*`usi_dict_type` 增加 MODULE 字段*/
ALTER TABLE `usi_dict_type` ADD MODULE VARCHAR(64); 
INSERT  INTO `usi_dict_type`(`ID`,`MODULE`,`CODE`,`MEMO`,`NAME`,`DEL_FLAG`,`CREATE_TIME`,`CREATE_USER`,`UPDATE_TIME`,`UPDATE_USER`) VALUES (10005,'system','CORE.MODULE','模块类型：系统管理','模块类型',NULL,NULL,'admin',NULL,NULL);
UPDATE `usi_dict_type` SET MODULE = 'system' WHERE ID IN(10001,10002,10003,10004,10006);

INSERT  INTO `usi_dict_entry`(`ID`,`CODE`,`ENABLED`,`NAME`,`ORDER_INDEX`,`DICT_TYPE_ID`,`DEL_FLAG`,`CREATE_TIME`,`CREATE_USER`,`UPDATE_TIME`,`UPDATE_USER`) VALUES (13,'system','Y','系统管理',1,10005,NULL,NULL,'admin',NULL,NULL);

/*`usi_resource` 增加 MODULE 字段*/
ALTER TABLE `usi_resource` ADD MODULE VARCHAR(64);

/*`usi_organization` 增加AREACODE字段*/
ALTER TABLE `usi_organization` ADD AREACODE VARCHAR(8);
INSERT  INTO `usi_dict_entry`(`ID`,`CODE`,`ENABLED`,`NAME`,`ORDER_INDEX`,`DICT_TYPE_ID`,`DEL_FLAG`,`CREATE_TIME`,`CREATE_USER`,`UPDATE_TIME`,`UPDATE_USER`) VALUES (14,'0551','Y','合肥',1,10007,NULL,NULL,'admin',NULL,NULL),(15,'0552','Y','蚌埠',2,10007,NULL,NULL,'admin',NULL,NULL),(16,'0553','Y','芜湖',3,10007,NULL,NULL,'admin',NULL,NULL);
INSERT  INTO `usi_dict_type`(`ID`,`MODULE`,`CODE`,`MEMO`,`NAME`,`DEL_FLAG`,`CREATE_TIME`,`CREATE_USER`,`UPDATE_TIME`,`UPDATE_USER`) VALUES (10007,'system','CORE.ORG.AREA','机构的所属区域','机构区域',NULL,NULL,NULL,NULL,NULL);
UPDATE `usi_organization` SET AREACODE = '0551' WHERE NAME='合肥';
UPDATE `usi_organization` SET AREACODE = '0552' WHERE NAME='蚌埠';
UPDATE `usi_organization` SET AREACODE = '0553' WHERE NAME='芜湖';