/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package cn.edu.ahpu.tpc.framework.web.model;
// Generated 2014-9-5 11:57:28 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TpcUser generated by hbm2java
 */
@Entity
@Table(name="tpc_user"
)
public class TpcUser  implements java.io.Serializable {


     private Long id;
     private String userCode;
     private String userName;
     private String password;
     private String salt;
     private Long areaId;
     private Long orgId;
     private String birthday;
     private Character gender;
     private String email;
     private String phoneNo;
     private String mphoneNo;
     private Integer errorCount;
     private Date lastLoginTime;
     private Date passwdInvalTime;
     private Date lockTime;
     private Integer delFlag;
     private Date createTime;
     private String createUser;
     private Date updateTime;
     private String updateUser;

    public TpcUser() {
    }

	
    public TpcUser(String userCode, String userName) {
        this.userCode = userCode;
        this.userName = userName;
    }
    public TpcUser(String userCode, String userName, String password, String salt, Long areaId, Long orgId, String birthday, Character gender, String email, String phoneNo, String mphoneNo, Integer errorCount, Date lastLoginTime, Date passwdInvalTime, Date lockTime, Integer delFlag, Date createTime, String createUser, Date updateTime, String updateUser) {
       this.userCode = userCode;
       this.userName = userName;
       this.password = password;
       this.salt = salt;
       this.areaId = areaId;
       this.orgId = orgId;
       this.birthday = birthday;
       this.gender = gender;
       this.email = email;
       this.phoneNo = phoneNo;
       this.mphoneNo = mphoneNo;
       this.errorCount = errorCount;
       this.lastLoginTime = lastLoginTime;
       this.passwdInvalTime = passwdInvalTime;
       this.lockTime = lockTime;
       this.delFlag = delFlag;
       this.createTime = createTime;
       this.createUser = createUser;
       this.updateTime = updateTime;
       this.updateUser = updateUser;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)
    
    @Column(name="ID", unique=true, nullable=false)
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="USER_CODE", nullable=false, length=64)
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    
    @Column(name="USER_NAME", nullable=false, length=64)
    public String getUserName() {
        return this.userName;
    }
    
    public void setUserName(String userName) {
        this.userName = userName;
    }
    
    @Column(name="PASSWORD", length=32)
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    
    @Column(name="SALT", length=32)
    public String getSalt() {
        return this.salt;
    }
    
    public void setSalt(String salt) {
        this.salt = salt;
    }
    
    @Column(name="AREA_ID")
    public Long getAreaId() {
        return this.areaId;
    }
    
    public void setAreaId(Long areaId) {
        this.areaId = areaId;
    }
    
    @Column(name="ORG_ID")
    public Long getOrgId() {
        return this.orgId;
    }
    
    public void setOrgId(Long orgId) {
        this.orgId = orgId;
    }
    
    @Column(name="BIRTHDAY", length=16)
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }
    
    @Column(name="GENDER", length=1)
    public Character getGender() {
        return this.gender;
    }
    
    public void setGender(Character gender) {
        this.gender = gender;
    }
    
    @Column(name="EMAIL", length=64)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    
    @Column(name="PHONE_NO", length=16)
    public String getPhoneNo() {
        return this.phoneNo;
    }
    
    public void setPhoneNo(String phoneNo) {
        this.phoneNo = phoneNo;
    }
    
    @Column(name="MPHONE_NO", length=16)
    public String getMphoneNo() {
        return this.mphoneNo;
    }
    
    public void setMphoneNo(String mphoneNo) {
        this.mphoneNo = mphoneNo;
    }
    
    @Column(name="ERROR_COUNT")
    public Integer getErrorCount() {
        return this.errorCount;
    }
    
    public void setErrorCount(Integer errorCount) {
        this.errorCount = errorCount;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LAST_LOGIN_TIME", length=19)
    public Date getLastLoginTime() {
        return this.lastLoginTime;
    }
    
    public void setLastLoginTime(Date lastLoginTime) {
        this.lastLoginTime = lastLoginTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="PASSWD_INVAL_TIME", length=19)
    public Date getPasswdInvalTime() {
        return this.passwdInvalTime;
    }
    
    public void setPasswdInvalTime(Date passwdInvalTime) {
        this.passwdInvalTime = passwdInvalTime;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOCK_TIME", length=19)
    public Date getLockTime() {
        return this.lockTime;
    }
    
    public void setLockTime(Date lockTime) {
        this.lockTime = lockTime;
    }
    
    @Column(name="DEL_FLAG")
    public Integer getDelFlag() {
        return this.delFlag;
    }
    
    public void setDelFlag(Integer delFlag) {
        this.delFlag = delFlag;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="CREATE_TIME", length=19)
    public Date getCreateTime() {
        return this.createTime;
    }
    
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }
    
    @Column(name="CREATE_USER", length=64)
    public String getCreateUser() {
        return this.createUser;
    }
    
    public void setCreateUser(String createUser) {
        this.createUser = createUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="UPDATE_TIME", length=19)
    public Date getUpdateTime() {
        return this.updateTime;
    }
    
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
    
    @Column(name="UPDATE_USER", length=64)
    public String getUpdateUser() {
        return this.updateUser;
    }
    
    public void setUpdateUser(String updateUser) {
        this.updateUser = updateUser;
    }




}
