package cn.edu.ahpu.tpc.framework.web.model.admin;
// Generated 2013-3-18 10:26:44 by Hibernate Tools 3.2.2.GA


import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * UsiLoginLog generated by hbm2java
 */
@Entity
@Table(name="TPC_LOGIN_LOG")
public class LoginLog  implements java.io.Serializable {


     private Long id;
     private String sessionId;
     private String orgName;
     private String userCode;
     private String clientType;
     private String ip;
     private Date loginDate;
     private Date logoutDate;
     private String loginStatus;

    public LoginLog() {
    }

	
    public LoginLog(String sessionId, String orgName, String userCode) {
        this.sessionId = sessionId;
        this.orgName = orgName;
        this.userCode = userCode;
    }
    public LoginLog(String sessionId, String orgName, String userCode, String clientType, String ip, Date loginDate, Date logoutDate, String loginStatus) {
       this.sessionId = sessionId;
       this.orgName = orgName;
       this.userCode = userCode;
       this.clientType = clientType;
       this.ip = ip;
       this.loginDate = loginDate;
       this.logoutDate = logoutDate;
       this.loginStatus = loginStatus;
    }
   
    @Id
    @Column(name="ID")
    @GeneratedValue(generator = "tableGenerator")     
	@GenericGenerator(name = "tableGenerator", strategy="cn.edu.ahpu.common.dao.key.SequenceGenerator")
    public Long getId() {
        return this.id;
    }
    
    public void setId(Long id) {
        this.id = id;
    }
    
    @Column(name="SESSION_ID", nullable=false, length=256)
    public String getSessionId() {
        return this.sessionId;
    }
    
    public void setSessionId(String sessionId) {
        this.sessionId = sessionId;
    }
    
    @Column(name="ORG_NAME", nullable=false, length=64)
    public String getOrgName() {
        return this.orgName;
    }
    
    public void setOrgName(String orgName) {
        this.orgName = orgName;
    }
    
    @Column(name="USER_CODE", nullable=false, length=64)
    public String getUserCode() {
        return this.userCode;
    }
    
    public void setUserCode(String userCode) {
        this.userCode = userCode;
    }
    
    @Column(name="CLIENT_TYPE", length=128)
    public String getClientType() {
        return this.clientType;
    }
    
    public void setClientType(String clientType) {
        this.clientType = clientType;
    }
    
    @Column(name="IP", length=64)
    public String getIp() {
        return this.ip;
    }
    
    public void setIp(String ip) {
        this.ip = ip;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOGIN_DATE", length=19)
    public Date getLoginDate() {
        return this.loginDate;
    }
    
    public void setLoginDate(Date loginDate) {
        this.loginDate = loginDate;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="LOGOUT_DATE", length=19)
    public Date getLogoutDate() {
        return this.logoutDate;
    }
    
    public void setLogoutDate(Date logoutDate) {
        this.logoutDate = logoutDate;
    }
    
    @Column(name="LOGIN_STATUS", length=64)
    public String getLoginStatus() {
        return this.loginStatus;
    }
    
    public void setLoginStatus(String loginStatus) {
        this.loginStatus = loginStatus;
    }




}


