/**
 * Copyright (c) 2012,USTC E-BUSINESS TECHNOLOGY CO.LTD All Rights Reserved.
 */
package cn.edu.ahpu.tpc.framework.web.model.admin;
// Generated 2013-8-9 9:54:42 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

import org.hibernate.annotations.GenericGenerator;

/**
 * UnteckBusiLog generated by hbm2java
 */
@Entity
@Table(name="TPC_BUSI_LOG"
)
public class UnteckBusiLog  implements java.io.Serializable {


     private Integer logId;
     private Integer optType;
     private String optContent;
     private Long optUser;
     private Date optTime;

    public UnteckBusiLog() {
    }

	
    public UnteckBusiLog(Integer logId) {
        this.logId = logId;
    }
    public UnteckBusiLog(Integer logId, Integer optType, String optContent, Long optUser, Date optTime) {
       this.logId = logId;
       this.optType = optType;
       this.optContent = optContent;
       this.optUser = optUser;
       this.optTime = optTime;
    }
   
    @Id 
    @GeneratedValue(generator = "tableGenerator")     
    @GenericGenerator(name = "tableGenerator", strategy="increment")       
    @Column(name="LOG_ID", unique=true, nullable=false)
    public Integer getLogId() {
        return this.logId;
    }
    
    public void setLogId(Integer logId) {
        this.logId = logId;
    }
    
    @Column(name="OPT_TYPE")
    public Integer getOptType() {
        return this.optType;
    }
    
    public void setOptType(Integer optType) {
        this.optType = optType;
    }
    
    @Column(name="OPT_CONTENT", length=4000)
    public String getOptContent() {
        return this.optContent;
    }
    
    public void setOptContent(String optContent) {
        this.optContent = optContent;
    }
    
    @Column(name="OPT_USER")
    public Long getOptUser() {
        return this.optUser;
    }
    
    public void setOptUser(Long optUser) {
        this.optUser = optUser;
    }
    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="OPT_TIME", length=26)
    public Date getOptTime() {
        return this.optTime;
    }
    
    public void setOptTime(Date optTime) {
        this.optTime = optTime;
    }




}
