-----PROMPT CREATING TPC_ATTACHMENT...
CREATE TABLE TPC_ATTACHMENT
(
  ID              INTEGER NOT NULL,
  FILE_NAME       VARCHAR(64),
  FILE_SIZE       INTEGER,
  FILE_TYPE       VARCHAR(32),
  ATTACHMENT_TYPE VARCHAR(32),
  DATA_ID         INTEGER,
  FILE_CODE       VARCHAR(64),
  DESCN           VARCHAR(256),
  DEL_FLAG        INTEGER,
  CREATE_TIME     TIMESTAMP,
  CREATE_USER     VARCHAR(64),
  UPDATE_TIME     TIMESTAMP,
  UPDATE_USER     VARCHAR(64)
)
;
ALTER TABLE TPC_ATTACHMENT
  ADD CONSTRAINT PRIMARYTPC_ATTACHMENT1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_DICT_ENTRY...
CREATE TABLE TPC_DICT_ENTRY
(
  ID           INTEGER NOT NULL,
  CODE         VARCHAR(64),
  ENABLED      CHAR(1),
  NAME         VARCHAR(64),
  ORDER_INDEX  INTEGER,
  DICT_TYPE_ID INTEGER,
  DEL_FLAG     INTEGER,
  CREATE_TIME  TIMESTAMP,
  CREATE_USER  VARCHAR(64),
  UPDATE_TIME  TIMESTAMP,
  UPDATE_USER  VARCHAR(64)
)
;
CREATE INDEX IDX_FK533311343A8CB7FBTPC_DICT ON TPC_DICT_ENTRY (DICT_TYPE_ID);
ALTER TABLE TPC_DICT_ENTRY
  ADD CONSTRAINT PRIMARYTPC_DICT_ENTRY1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_DICT_TYPE...
CREATE TABLE TPC_DICT_TYPE
(
  ID          INTEGER NOT NULL,
  MODULE      VARCHAR(64),
  CODE        VARCHAR(64),
  MEMO        VARCHAR(256),
  NAME        VARCHAR(64),
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
ALTER TABLE TPC_DICT_TYPE
  ADD CONSTRAINT PRIMARYTPC_DICT_TYPE1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_LOGIN_LOG...
CREATE TABLE TPC_LOGIN_LOG
(
  ID           INTEGER NOT NULL,
  SESSION_ID   VARCHAR(256),
  ORG_NAME     VARCHAR(64),
  USER_CODE    VARCHAR(64),
  CLIENT_TYPE  VARCHAR(128),
  IP           VARCHAR(64),
  LOGIN_DATE   TIMESTAMP,
  LOGOUT_DATE  TIMESTAMP,
  LOGIN_STATUS VARCHAR(64)
)
;
ALTER TABLE TPC_LOGIN_LOG
  ADD CONSTRAINT PRIMARYTPC_LOGIN_LOG1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_MENU...
CREATE TABLE TPC_MENU
(
  ID          INTEGER NOT NULL,
  DESCN       VARCHAR(256),
  ICONCLS     VARCHAR(30),
  ISLEAF      CHAR(1),
  LEVEL_      INTEGER,
  MENUSEQ     VARCHAR(128),
  NAME        VARCHAR(64),
  PARENTID    INTEGER,
  THESORT     INTEGER,
  RESOURCE_ID INTEGER,
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
CREATE INDEX IDX_FKBB5B107D3B1AA04ETPC_MENU ON TPC_MENU (RESOURCE_ID);
ALTER TABLE TPC_MENU
  ADD CONSTRAINT PRIMARYTPC_MENU1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_OPERATION...
CREATE TABLE TPC_OPERATION
(
  ID          INTEGER NOT NULL,
  CODE        VARCHAR(64),
  MEMO        VARCHAR(256),
  NAME        VARCHAR(64),
  ORDER_INDEX INTEGER,
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
ALTER TABLE TPC_OPERATION
  ADD CONSTRAINT PRIMARYTPC_OPERATION1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_ORGANIZATION...
CREATE TABLE TPC_ORGANIZATION
(
  ID          INTEGER NOT NULL,
  LEVEL_      INTEGER,
  NAME        VARCHAR(64),
  AREACODE	  VARCHAR(8),
  ORGSEQ      VARCHAR(128),
  PARENTID    INTEGER,
  THESORT     INTEGER,
  DESCN       VARCHAR(256),
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
ALTER TABLE TPC_ORGANIZATION
  ADD CONSTRAINT PRIMARYTPC_ORGANIZATION1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_PRIMARYKEY...
CREATE TABLE TPC_PRIMARYKEY
(
  CODE INTEGER NOT NULL,
  NAME VARCHAR(30) NOT NULL
)
;
ALTER TABLE TPC_PRIMARYKEY
  ADD CONSTRAINT PRIMARYTPC_PRIMARYKEY1 PRIMARY KEY (CODE, NAME);

-----PROMPT CREATING TPC_RESOURCE...
CREATE TABLE TPC_RESOURCE
(
  ID          INTEGER NOT NULL,
  MODULE      VARCHAR(64),
  NAME        VARCHAR(64),
  ACTION      VARCHAR(128),
  DESCN       VARCHAR(256),
  ENABLED     CHAR(1),
  PRIORITY    INTEGER,
  TYPE        VARCHAR(32),
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
ALTER TABLE TPC_RESOURCE
  ADD CONSTRAINT PRIMARYTPC_RESOURCE1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_ROLE...
CREATE TABLE TPC_ROLE
(
  ID          INTEGER NOT NULL,
  CODE        VARCHAR(64),
  NAME        VARCHAR(64),
  ENABLED     CHAR(1),
  DESCN       VARCHAR(256),
  DEL_FLAG    INTEGER,
  CREATE_TIME TIMESTAMP,
  CREATE_USER VARCHAR(64),
  UPDATE_TIME TIMESTAMP,
  UPDATE_USER VARCHAR(64)
)
;
ALTER TABLE TPC_ROLE
  ADD CONSTRAINT PRIMARYTPC_ROLE1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_ROLE_RESOURCE...
CREATE TABLE TPC_ROLE_RESOURCE
(
  ROLE_ID     INTEGER NOT NULL,
  RESOURCE_ID INTEGER NOT NULL
)
;
ALTER TABLE TPC_ROLE_RESOURCE
  ADD CONSTRAINT PRIMARYTPC_ROLE_RESOURCE1 PRIMARY KEY (ROLE_ID, RESOURCE_ID);

-----PROMPT CREATING TPC_USER...
CREATE TABLE TPC_USER
(
  ID                INTEGER NOT NULL,
  USER_CODE         VARCHAR(64),
  USER_NAME         VARCHAR(64),
  PASSWORD          VARCHAR(32),
  SALT              VARCHAR(32),
  AREA_ID           INTEGER,
  ORG_ID            INTEGER,
  BIRTHDAY          VARCHAR(16),
  GENDER            CHAR(1),
  EMAIL             VARCHAR(64),
  PHONE_NO          VARCHAR(16),
  MPHONE_NO         VARCHAR(16),
  ERROR_COUNT       INTEGER,
  LAST_LOGIN_TIME   TIMESTAMP,
  PASSWD_INVAL_TIME TIMESTAMP,
  LOCK_TIME         TIMESTAMP,
  DEL_FLAG          INTEGER,
  CREATE_TIME       TIMESTAMP,
  CREATE_USER       VARCHAR(64),
  UPDATE_TIME       TIMESTAMP,
  UPDATE_USER       VARCHAR(64)
)
;
ALTER TABLE TPC_USER
  ADD CONSTRAINT PRIMARYTPC_USER1 PRIMARY KEY (ID);

-----PROMPT CREATING TPC_USER_ROLE...
CREATE TABLE TPC_USER_ROLE
(
  USER_ID INTEGER NOT NULL,
  ROLE_ID INTEGER NOT NULL
)
;
ALTER TABLE TPC_USER_ROLE
  ADD CONSTRAINT PRIMARYTPC_USER_ROLE1 PRIMARY KEY (USER_ID, ROLE_ID);
  
-----PROMPT LOADING TPC_ATTACHMENT...
-----PROMPT TABLE IS EMPTY
-----PROMPT LOADING TPC_DICT_ENTRY...
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, 'M', 'Y', '��', 1, 10001, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, 'F', 'Y', 'Ů', 2, 10001, NULL, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (3, 'N', 'Y', 'δ֪', 3, 10001, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (4, 'Y', 'Y', 'Ҷ�ӽڵ�', 1, 10002, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (5, 'N', 'Y', '��Ҷ�ӽڵ�', 2, 10002, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (6, 'Y', 'Y', '��Ч', 1, 10003, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (7, 'N', 'Y', '��Ч', 2, 10003, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (8, 'menu', 'Y', '�˵�', 1, 10004, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (9, 'uri', 'Y', 'URI', 2, 10004, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10, 'method', 'Y', '����', 3, 10004, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (11, 'FLOW', 'Y', '������', 1, 10006, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_DICT_ENTRY (ID, CODE, ENABLED, NAME, ORDER_INDEX, DICT_TYPE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (12, 'SUBFLOW', 'Y', '������', 2, 10006, NULL, NULL, NULL, NULL, NULL);
INSERT  INTO TPC_DICT_ENTRY(ID,CODE,ENABLED,NAME,ORDER_INDEX,DICT_TYPE_ID,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER) 
VALUES (13, 'system', 'Y', 'ϵͳ����',1,10005,NULL,NULL,'admin',NULL,NULL);
INSERT  INTO TPC_DICT_ENTRY(ID,CODE,ENABLED,NAME,ORDER_INDEX,DICT_TYPE_ID,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER)
VALUES (14,'0551','Y','�Ϸ�',1,10007,NULL,NULL,'admin',NULL,NULL);
INSERT  INTO TPC_DICT_ENTRY(ID,CODE,ENABLED,NAME,ORDER_INDEX,DICT_TYPE_ID,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER)
VALUES (15,'0552','Y','����',2,10007,NULL,NULL,'admin',NULL,NULL);
INSERT  INTO TPC_DICT_ENTRY(ID,CODE,ENABLED,NAME,ORDER_INDEX,DICT_TYPE_ID,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER)
VALUES (16,'0553','Y','�ߺ�',3,10007,NULL,NULL,'admin',NULL,NULL);
COMMIT;
-----PROMPT 12 RECORDS LOADED
-----PROMPT LOADING TPC_DICT_TYPE...
INSERT INTO TPC_DICT_TYPE (ID, MODULE, CODE, MEMO, NAME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10001, 'system', 'CORE.GENDER', '�Ա��С�Ů��δ֪', '�Ա�', NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_DICT_TYPE (ID, MODULE, CODE, MEMO, NAME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10002, 'system', 'CORE.NODE.TYPE', '�ڵ����ͣ�Ҷ�ӽڵ�ͷ�Ҷ�ӽڵ�', '�ڵ�����', NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_DICT_TYPE (ID, MODULE, CODE, MEMO, NAME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10003, 'system', 'CORE.ENABLED', '״̬��Ч�ԣ���Ч����Ч', '״̬��Ч��', NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_DICT_TYPE (ID, MODULE, CODE, MEMO, NAME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10004, 'system', 'CORE.RESOURCE.TYPE', '��Դ���ͣ�URI���������˵�', '��Դ����', NULL, NULL, NULL, NULL, NULL);
INSERT  INTO TPC_DICT_TYPE(ID, MODULE,CODE,MEMO,NAME,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER) 
VALUES (10005, 'system', 'CORE.MODULE','ģ�����ͣ�ϵͳ����','ģ������',NULL,NULL,'admin',NULL,NULL);
INSERT INTO TPC_DICT_TYPE (ID, MODULE, CODE, MEMO, NAME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10006, 'system', 'CORE.FLOW.TYPE', '��������', '��������', NULL, NULL, NULL, NULL, NULL);
INSERT  INTO TPC_DICT_TYPE(ID, MODULE,CODE,MEMO,NAME,DEL_FLAG,CREATE_TIME,CREATE_USER,UPDATE_TIME,UPDATE_USER) VALUES
(10007,'system','CORE.ORG.AREA','�����������','������',NULL,NULL,NULL,NULL,NULL);
COMMIT;
-----PROMPT 5 RECORDS LOADED
-----PROMPT LOADING TPC_LOGIN_LOG...
-----PROMPT TABLE IS EMPTY
-----PROMPT LOADING TPC_MENU...
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, '21', NULL, 'N', 1, NULL, 'ϵͳ����', 0, 2, 12, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, '��Դ����', NULL, 'Y', 2, NULL, '��Դ����', 1, 4, 5, NULL, NULL, NULL, TO_TIMESTAMP('19-11-2011 13:36:37', 'DD-MM-YYYY HH24:MI:SS'), 'admin');
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (3, NULL, NULL, 'Y', 2, NULL, '�˵�����', 1, 6, 6, NULL, NULL, NULL, NULL, 'admin');
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (4, NULL, NULL, 'Y', 2, NULL, '��ɫ����', 1, 3, 7, NULL, NULL, NULL, NULL, 'admin');
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (5, '�����', NULL, 'Y', 2, NULL, '�����', 1, 1, 8, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (7, '�û�����', NULL, 'Y', 2, NULL, '�û�����', 1, 2, 10, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (8, 'ҵ���ֵ�', NULL, 'Y', 2, NULL, 'ҵ���ֵ�', 1, 7, 11, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10, '���˹�����', NULL, 'N', 1, NULL, '���˹�����', 0, 1, 15, NULL, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (171, NULL, NULL, 'Y', 2, NULL, '�ļ�����', 1, 7, 221, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (181, NULL, NULL, 'Y', 2, NULL, '��־����', 1, 8, 231, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_MENU (ID, DESCN, ICONCLS, ISLEAF, LEVEL_, MENUSEQ, NAME, PARENTID, THESORT, RESOURCE_ID, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (182, NULL, NULL, 'Y', 2, NULL, 'SQL����', 1, 9, 232, NULL, NULL, NULL, NULL, NULL);
COMMIT;
-----PROMPT 19 RECORDS LOADED
-----PROMPT LOADING TPC_OPERATION...
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, 'CORE.ADD', '���', '���', NULL, NULL, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, 'CORE.UPTIMESTAMP', '����', '����', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (3, 'CORE.REMOVE', 'ɾ��', 'ɾ��', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (4, 'CORE.AUTHROLE', '�����ɫ', '�����ɫ', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (5, 'CORE.AUTHRESOURCE', '������Դ', '������Դ', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (6, 'CORE.AUTHUSER', '��Ȩ�û�', '��Ȩ�û�', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (7, 'CORE.ADDSIBLINGNODE', '���ͬ���ڵ�', '���ͬ���ڵ�', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (8, 'CORE.ADDCHILDNODE', '����ӽڵ�', '����ӽڵ�', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (9, 'CORE.UPTIMESTAMPNODE', '���½ڵ�', '���½ڵ�', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10, 'CORE.REMOVENODE', 'ɾ��ڵ�', 'ɾ��ڵ�', NULL, NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_OPERATION (ID, CODE, MEMO, NAME, ORDER_INDEX, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (11, 'CORE.ORDERNODE', '�ڵ�����', '�ڵ�����', NULL, NULL, NULL, 'admin', NULL, NULL);
COMMIT;
-----PROMPT 11 RECORDS LOADED
-----PROMPT LOADING TPC_ORGANIZATION...
INSERT INTO TPC_ORGANIZATION (ID, LEVEL_, NAME, AREACODE, ORGSEQ, PARENTID, THESORT, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, 1, '���յ���', NULL, '1.', 0, 1, '���յ���', 0, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_ORGANIZATION (ID, LEVEL_, NAME, AREACODE, ORGSEQ, PARENTID, THESORT, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, 2, '�Ϸ�', '0551', '1.2.', 1, 1, '�Ϸ�', 0, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_ORGANIZATION (ID, LEVEL_, NAME, AREACODE, ORGSEQ, PARENTID, THESORT, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (3, 2, '����', '0552', '1.3.', 1, 2, '����', 0, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_ORGANIZATION (ID, LEVEL_, NAME, AREACODE, ORGSEQ, PARENTID, THESORT, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (4, 2, '�ߺ�', '0553', '1.4.', 1, 3, '�ߺ�', 0, NULL, 'admin', NULL, 'admin');
COMMIT;
-----PROMPT 4 RECORDS LOADED
-----PROMPT LOADING TPC_PRIMARYKEY...
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (10, 'TPC_ATTACHMENT');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (10, 'TPC_ROLE');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (10, 'TPC_LOGIN_LOG');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (30, 'TPC_CONFIG');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (30, 'TPC_DICT_TYPE');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (40, 'TPC_ORGANIZATION');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (60, 'BUSINESSSTARFLOW');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (80, 'TEST_FLOW_LEAVE');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (90, 'TPC_OPERATION');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (100, 'TPC_USER');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (170, 'TPC_DICT_ENTRY');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (190, 'TPC_MENU');
INSERT INTO TPC_PRIMARYKEY (CODE, NAME)
VALUES (240, 'TPC_RESOURCE');
COMMIT;
-----PROMPT 13 RECORDS LOADED
-----PROMPT LOADING TPC_RESOURCE...
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (4, '��������', '/**', NULL, 'Y', 999, 'uri', NULL, NULL, NULL, NULL, 'admin');
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (5, '��Դ����', './resource/index', 'Ȩ�޹���', 'Y', 4, 'menu', NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (6, '�˵�����', './menu/index', NULL, 'Y', 5, 'menu', NULL, NULL, NULL, NULL, 'admin');
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (7, '��ɫ����', './role/index', NULL, 'Y', 6, 'menu', NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (8, '�����', './org/index', '�����', 'Y', 7, 'menu', NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (10, '�û�����', './user/index', '�û�����', 'Y', 9, 'menu', NULL, NULL, 'admin', NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (11, 'ҵ���ֵ�', './dict/index', 'ҵ���ֵ�', 'Y', 10, 'menu', NULL, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (12, 'ϵͳ����', '/systemadmin', 'ϵͳ����', 'Y', 11, 'menu', NULL, NULL, NULL, NULL, 'admin');
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (15, '���˹�����', '/workspace', '���˹�����', 'Y', 13, 'menu', NULL, NULL, 'admin', NULL, 'admin');
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (221, '�ļ�����', '/attachment/index', NULL, 'Y', 7, 'menu', NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (231, '��־����', '/loginLog/index', NULL, 'Y', 8, 'menu', NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_RESOURCE (ID, NAME, ACTION, DESCN, ENABLED, PRIORITY, TYPE, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (232, 'SQL����', '/schemaVersion/index', NULL, 'Y', 9, 'menu', NULL, NULL, NULL, NULL, NULL);
COMMIT;
-----PROMPT 21 RECORDS LOADED
-----PROMPT LOADING TPC_ROLE...
INSERT INTO TPC_ROLE (ID, CODE, NAME, ENABLED, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, 'ROLE_ADMIN', '����Ա��ɫ', 'Y', NULL, NULL, NULL, NULL, NULL, NULL);
INSERT INTO TPC_ROLE (ID, CODE, NAME, ENABLED, DESCN, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, 'ROLE_USER', '��ͨ�û�', 'Y', NULL, NULL, NULL, NULL, NULL, NULL);
COMMIT;
-----PROMPT 2 RECORDS LOADED
-----PROMPT LOADING TPC_ROLE_RESOURCE...
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 4);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 5);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 6);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 7);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 8);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 10);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 11);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 12);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 15);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 25);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 221);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 231);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (1, 232);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (2, 221);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (2, 231);
INSERT INTO TPC_ROLE_RESOURCE (ROLE_ID, RESOURCE_ID)
VALUES (2, 232);
COMMIT;
-----PROMPT 25 RECORDS LOADED
-----PROMPT LOADING TPC_USER...
INSERT INTO TPC_USER (ID, USER_CODE, USER_NAME, PASSWORD, SALT, AREA_ID, ORG_ID, BIRTHDAY, GENDER, EMAIL, PHONE_NO, MPHONE_NO, ERROR_COUNT, LAST_LOGIN_TIME, PASSWD_INVAL_TIME, LOCK_TIME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (1, 'admin', 'ϵͳ����Ա', 'd6d252bac8e22d4db7e11db4a3a6db1d', '6gilcjmzowo6vav1lxmqd6cmograasqq', 1, 1, NULL, 'F', 'BSLI123@HOTMAIL.COM', NULL, NULL, 0, TO_TIMESTAMP('20-03-2013 13:44:08', 'DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 0, TO_TIMESTAMP('26-11-2011 09:27:52', 'DD-MM-YYYY HH24:MI:SS'), 'ANONYMOUSUSER', TO_TIMESTAMP('26-11-2011 08:31:06', 'DD-MM-YYYY HH24:MI:SS'), 'admin');
INSERT INTO TPC_USER (ID, USER_CODE, USER_NAME, PASSWORD, SALT, AREA_ID, ORG_ID, BIRTHDAY, GENDER, EMAIL, PHONE_NO, MPHONE_NO, ERROR_COUNT, LAST_LOGIN_TIME, PASSWD_INVAL_TIME, LOCK_TIME, DEL_FLAG, CREATE_TIME, CREATE_USER, UPDATE_TIME, UPDATE_USER)
VALUES (2, 'unteck', '��ͨ�û�', 'd6d252bac8e22d4db7e11db4a3a6db1d', '6gilcjmzowo6vav1lxmqd6cmograasqq', 2, 2, NULL, 'M', 'BSLI123@HOTMAIL.COM', NULL, NULL, 0, TO_TIMESTAMP('06-09-2012 11:31:07', 'DD-MM-YYYY HH24:MI:SS'), NULL, NULL, 0, TO_TIMESTAMP('26-11-2011 09:27:52', 'DD-MM-YYYY HH24:MI:SS'), 'ANONYMOUSUSER', TO_TIMESTAMP('26-11-2011 08:31:06', 'DD-MM-YYYY HH24:MI:SS'), 'admin');
COMMIT;
-----PROMPT 2 RECORDS LOADED
-----PROMPT LOADING TPC_USER_ROLE...
INSERT INTO TPC_USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 1);
INSERT INTO TPC_USER_ROLE (USER_ID, ROLE_ID)
VALUES (1, 2);
INSERT INTO TPC_USER_ROLE (USER_ID, ROLE_ID)
VALUES (2, 2);
COMMIT;
-----PROMPT 3 RECORDS LOADED